### ISSUE TITLE
Midi Noten detector

### ISSUE THREAD

**Issue by TheNeoGameFactory** [TheNeoGameFactory/Trijam-67-Disco-Pizza-Service#2]
Sind wir schon dran und Jonathan weiß schon wie.

Jonathan, bitte Signale mit einbinden, am besten verschiedene, dann kann bei jedem Signal was anderes passieren.

**Comment by jonathan-wolt** [comment]
genau das war mein Plan :) 
soll ich mehrere Signale machen, oder ein Signal mit einem Prameter, dem ich halt dann den Typ übergebe?

**Comment by TheNeoGameFactory** [comment]
Hm, mehrere wäre glaube besser oder? 🤔
Dann kann man immer direkt da anknüpfen
